### ISSUE TITLE
Add Unit Testing

### ISSUE THREAD

**Issue by raybesiga** [sparkplug/momoapi-python#4]
**Problem**

Most of the code currently in `master` is not tested. This means it will be hard to detect when this library starts to fail.

**Solution**

To ensure that the library behaves as expected, we need to add tests.
 
**Tasks**

- [x] setup testing suite
- [x] add unit tests for collections, disbursements, remittances
- [x] add unit tests for users
